### ISSUE TITLE
do you have some description about forgetting mechanism

### ISSUE THREAD

**Issue by Sandy4321** [CodeLionX/pyonlinesvr#2] opened 2021-06-30 16:29 UTC
do you have some description about forgetting mechanism

how fast data from fast stopes to influence on inference
for example compare with    
https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVR.html

seems to be in LinearSVR we can train the same model several times to do incremental training - warm start

**Comment by CodeLionX** [comment] 2021-07-01 07:42
In my understanding sklearn does not fully support online learning, i.e., the sklearn regressors have no forgetting mechanism. You can use incremental learning to add more training samples to the regressor in batches, but this does not include a forgetting mechanism and is limited to selected methods [[1]]. [LinearSVR](https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVR.html) is not part of this list, because it has no `partial_fit` method.

PyOnlineSVR is different. It supports incremental  learning using `partial_fit` and explicitly exposes a [`forget` method](https://github.com/CodeLionX/pyonlinesvr/blob/main/pyonlinesvr/osvr.py#L299) to remove samples from the training data / from the fit. Francesco calls this forgetting mechanism unlearning and explains it in detail on his website [[2], Section 2 The Unlearning Algorithm] and in his thesis [[3], Section 5.2 The Unlearning Algorithm].

You can use PyOnlineSVR for all 3 cases:

```python
>>> import numpy as np
>>> from pyonlinesvr import OnlineSVR
>>> X = np.array([[0, 0], [2, 2]])
>>> y = np.array([0.5, 2.5])

# Batch learning:
>>> batch_regr = OnlineSVR()
>>> batch_regr.fit(X, y)
OnlineSVR()
>>> batch_regr.predict([[1, 1]])
array([ 1.5])

# Incremental learning:
>>> incremental_regr = OnlineSVR()
>>> incremental_regr.partial_fit(X[:1], y[:1])
OnlineSVR()
>>> incremental_regr.partial_fit(X[1:], y[1:])
OnlineSVR()
>>> incremental_regr.predict([[1, 1]])
array([ 1.5])

# Online learning (incremental + forgetting):
>>> online_regr = OnlineSVR()
>>> online_regr.fit(X, y)
OnlineSVR()
>>> batch_regr.predict([[1, 1]])
array([ 1.5])
>>> online_regr.partial_fit([[4, 4]], [4.5])
OnlineSVR()
>>> online_regr.predict([[3, 3]])
array([ 3.19873654])
>>> online_regr.forget(X[:1])
>>> online_regr.predict([[3, 3]])
array([ 3.5])
```

[1]: https://scikit-learn.org/stable/computing/scaling_strategies.html?highlight=online%20learning#incremental-learning
[2]: http://onlinesvr.altervista.org/Theory/Theory%20-%2003%20-%20Psuedocode%20Algorithm.htm
[3]: http://onlinesvr.altervista.org/Research/Online%20Support%20Vector%20Regression%20(Parrella%20F.)%20[2007].pdf

**Comment by CodeLionX** [comment] 2021-08-02 13:17
It seems that I could answer your question. I close this issue now. If you have another question, please open a new issue, thanks.

**Closed by CodeLionX** 2021-08-02 13:17 UTC
Labels: question
